apiVersion: v1
kind: Service
metadata:
  name: compound-file-service
spec:
  type: ClusterIP
  selector:
    app: compound-file
  ports:
    - port: 80
      targetPort: comp-file-port
      name: compound-file-service-port
      protocol: TCP

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: compound-file-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: compound-file
  template:
    metadata:
      name: compound-file-pod
      labels:
        app: compound-file
    spec:
      nodeName: control-plane
      containers:
        - name: compound-file-container
          image: aprijalghiyas/herbalchem-compound-file-service:1.4
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: comp-file-port
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "kubernetes"
            - name: CONFIG_SERVER_USERNAME
              value: "herbalchem"
            - name: CONFIG_SERVER_PASSWORD
              value: "herbalchem"
            - name: CONFIG_SERVER_HOST
              value: "cf-server-service/config-server"
          volumeMounts:
            - mountPath: /structure
              name: compound-file-storage
          resources:
            limits:
              memory: 256Mi
#          lifecycle:
#            postStart:
#              exec:
#                command: ["/bin/sh", "-c", "mkdir -p /structure/structure_2d_sdf /structure/structure_3d_sdf"]
      volumes:
        - name: compound-file-storage
          persistentVolumeClaim:
            claimName: compound-file-pvc
