apiVersion: v1
kind: PersistentVolume
metadata:
  name: compound-file-pv
spec:
  storageClassName: compound-file
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/structure"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: compound-file-pvc
spec:
  storageClassName: compound-file
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
