apiVersion: v1
kind: PersistentVolume
metadata:
  name: elasticsearch-pv
spec:
  storageClassName: elasticsearch
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/aprijal_99/elasticsearch/data"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elasticsearch-pvc
spec:
  storageClassName: elasticsearch
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi

---

apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-service
spec:
  type: ClusterIP
  selector:
    app: elasticsearch
  ports:
    - port: 80
      targetPort: es-port
      name: elasticsearch-service-port
      protocol: TCP

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      name: elasticsearch-pod
      labels:
        app: elasticsearch
    spec:
      nodeName: control-plane
      containers:
        - name: elasticsearch-container
          image: bitnami/elasticsearch:7.17.7
          imagePullPolicy: IfNotPresent
          env:
            - name: ELASTICSEARCH_CLUSTER_NAME
              value: "herbalchem-es-cluster"
            - name: ELASTICSEARCH_NODE_NAME
              value: "es-node-1"
            - name: ELASTICSEARCH_PORT_NUMBER
              value: "9200"
            - name: ELASTICSEARCH_HEAP_SIZE
              value: "3072m"
          ports:
            - containerPort: 9200
              name: es-port
          volumeMounts:
            - mountPath: /bitnami/elasticsearch/data
              name: elasticsearch-data-storage
            - mountPath: /opt/bitnami/elasticsearch/config/my_elasticsearch.yml
              subPath: my_elasticsearch.yml
              name: elasticsearch-config
      volumes:
        - name: elasticsearch-data-storage
          persistentVolumeClaim:
            claimName: elasticsearch-pvc
        - name: elasticsearch-config
          configMap:
            name: elasticsearch-configmap

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: elasticsearch-configmap
data:
  my_elasticsearch.yml: |
    http:
      cors:
        enabled: true
        allow-origin: "*"
        allow-methods: OPTIONS, HEAD, GET, POST, PUT, DELETE
        allow-headers: X-Requested-With,X-Auth-Token,Content-Type,Content-Length
        allow-credentials: true
