apiVersion: v1
kind: Service
metadata:
  name: kafka-service
spec:
  type: ClusterIP
  selector:
    app: zookeeper
  ports:
    - port: 9092
      targetPort: kafka-port
      protocol: TCP
      name: kafka-service-port

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      name: kafka-pod
      labels:
        app: kafka
    spec:
      nodeName: spring-boot-microservices
      containers:
        - name: kafka-container
          image: confluentinc/cp-kafka:latest
          imagePullPolicy: Always
          env:
            - name: KAFKA_BROKER_ID
              value: "1"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: "zookeeper-service:2181"
            - name: KAFKA_LISTENERS
              value: "EXTERNAL_DIFFERENT_HOST://:9092"
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "EXTERNAL_DIFFERENT_HOST://kafka-service:9092"
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: "EXTERNAL_DIFFERENT_HOST:PLAINTEXT"
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: "EXTERNAL"
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "1"
            - name: KAFKA_TRANSACTION_STATE_LOG_MIN_ISR
              value: "1"
            - name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
              value: "1"
          ports:
            - containerPort: 9092
              name: kafka-port
