apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: services-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - herbalchem.site
      secretName: herbalchem-tls
  rules:
#    - host: phpmyadmin.herbalchem.site
#      http:
#        paths:
#          - path: /
#            pathType: Prefix
#            backend:
#              service:
#                name: phpmyadmin-service
#                port:
#                  number: 80
#    - host: elasticsearch.herbalchem.site
#      http:
#        paths:
#          - path: /
#            pathType: Prefix
#            backend:
#              service:
#                name: elasticsearch-service
#                port:
#                  number: 80
#    - host: www.herbalchem.site
#      http:
#        paths:
#          - path: /authorization-server
#            pathType: Prefix
#            backend:
#              service:
#                name: auth-server-service
#                port:
#                  number: 8921
#          - path: /
#            pathType: Prefix
#            backend:
#              service:
#                name: frontend-service
#                port:
#                  number: 80
    - host: herbalchem.site
      http:
        paths:
          - path: /authorization-server
            pathType: Prefix
            backend:
              service:
                name: auth-server-service
                port:
                  number: 8921
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-service
                port:
                  number: 80
