apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: services-ingress
  annotations:
#    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - herbalchem.site
        - www.herbalchem.site
      secretName: herbalchem.site-tls
  rules:
    - host: www.herbalchem.site
      http:
        paths:
          - path: /phpmyadmin
            pathType: Prefix
            backend:
              service:
                name: phpmyadmin-service
                port:
                  number: 80
          - path: /compound_summary
            pathType: Prefix
            backend:
              service:
                name: elasticsearch-service
                port:
                  number: 80
          - path: /authorization-server
            pathType: Prefix
            backend:
              service:
                name: auth-server-service
                port:
                  number: 8921
          - path: /compound-detail
            pathType: Prefix
            backend:
              service:
                name: compound-detail-service
                port:
                  number: 80
          - path: /compound-form
            pathType: Prefix
            backend:
              service:
                name: gateway-service
                port:
                  number: 80
          - path: /compound-file
            pathType: Prefix
            backend:
              service:
                name: gateway-service
                port:
                  number: 80
          - path: /compound-detail
            pathType: Prefix
            backend:
              service:
                name: gateway-service
                port:
                  number: 80
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-service
                port:
                  number: 80
    - host: herbalchem.site
      http:
        paths:
          - path: /phpmyadmin
            pathType: Prefix
            backend:
              service:
                name: phpmyadmin-service
                port:
                  number: 80
          - path: /compound_summary
            pathType: Prefix
            backend:
              service:
                name: elasticsearch-service
                port:
                  number: 80
          - path: /authorization-server
            pathType: Prefix
            backend:
              service:
                name: auth-server-service
                port:
                  number: 8921
          - path: /compound-detail
            pathType: Prefix
            backend:
              service:
                name: compound-detail-service
                port:
                  number: 80
          - path: /compound-form
            pathType: Prefix
            backend:
              service:
                name: gateway-service
                port:
                  number: 80
          - path: /compound-file
            pathType: Prefix
            backend:
              service:
                name: gateway-service
                port:
                  number: 80
          - path: /compound-detail
            pathType: Prefix
            backend:
              service:
                name: gateway-service
                port:
                  number: 80
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-service
                port:
                  number: 80
