apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: client-ingress
spec:
  ingressClassName: nginx
  rules:
    - host: ghiyas.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: phpmyadmin-service
                port:
                  number: 8
          - path: /client
            pathType: Prefix
            backend:
              service:
                name: client-service
                port:
                  number: 80