apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-app
  template:
    metadata:
      name: kafka-app-pod
      labels:
        app: kafka-app
    spec:
      nodeName: control-plane
      containers:
        - name: kafka-app-container
          image: aprijalghiyas/spring-kafka-app:1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 10987
              name: kafka-app-port
