apiVersion: v1
kind: Service
metadata:
  name: zookeeper-service
spec:
  type: ClusterIP
  selector:
    app: zookeeper
  ports:
    - port: 2181
      targetPort: zookeeper-port
      protocol: TCP
      name: zookeeper-service-port

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      name: zookeeper-pod
      labels:
        app: zookeeper
    spec:
      nodeName: spring-boot-microservices
      containers:
        - name: zookeeper-container
          image: confluentinc/cp-zookeeper:latest
          imagePullPolicy: Always
          env:
            - name: ZOOKEEPER_CLIENT_PORT
              value: "2181"
            - name: ZOOKEEPER_TICK_TIME
              value: "2000"
          ports:
            - containerPort: 2181
              name: zookeeper-port