apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: herbalchem.site
spec:
  secretName: herbalchem.site-tls
  issuerRef:
    name: letsencrypt-prod
    kind: Issuer
  commonName: herbalchem.site
  dnsNames:
    - herbalchem.site
    - www.herbalchem.site
